In [1]:
import numpy as np
import pandas as pd
import os
import torch

In [2]:
# broadcasting

In [4]:
# In torch broadcasting, the operations happen in an elemen-wise fashion - meaning this is not equal to matrix multiplication "*"

# The broadcasting happens in the singleton dimension, if there exist one such dimension (the axis that has a dimenison of 1). We basically strech the contents along this axis.

In [5]:
# consider the following example

In [7]:
x = torch.randn((3,1))

In [8]:
x

tensor([[1.7959],
        [1.1171],
        [0.1500]])

In [9]:
x.shape

torch.Size([3, 1])

In [10]:
y = torch.randn((1,3))

In [11]:
y

tensor([[-1.1303, -0.1305,  0.3660]])

In [12]:
x*y

tensor([[-2.0298, -0.2344,  0.6573],
        [-1.2626, -0.1458,  0.4089],
        [-0.1696, -0.0196,  0.0549]])

In [13]:
y*x

tensor([[-2.0298, -0.2344,  0.6573],
        [-1.2626, -0.1458,  0.4089],
        [-0.1696, -0.0196,  0.0549]])

In [14]:
# note both of these return the same output

In [15]:
# What happense here?

In [18]:
# # x has dimensions 3*1. The contensts are strched column-wise
# # therefore x becomes
# x = [1.7959 1.7959 1.7959
#      1.1171 1.1171 1.1171
#      0.1500 0.1500 0.1500
# ]
# # y is stretched along row axis

# y  =  [-1.1303 -0.1305  0.3660
#        -1.1303 -0.1305 0.3660
#        -1.1303 -0.1305 0.3660]

# # now the element-wise multiplication

In [19]:
# the first row should look something like this
-1.1303*1.7959, -0.1305*1.7959,  0.3660*1.7959

(-2.02990577, -0.23436495000000002, 0.6572994)

In [20]:
1.1171*-1.1303, 1.1171*-0.1305, 1.1171* 0.3660

(-1.2626581300000002, -0.14578155, 0.40885859999999996)

In [21]:
-1.1303*0.1500, -0.1305*0.1500, 0.3660*0.1500

(-0.169545, -0.019575, 0.0549)