In [1]:
import torch
import numpy as np
import os

In [2]:
# Are we on GPU?

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.get_device_name()

'Tesla V100S-PCIE-32GB'

#### Tensors

In [7]:
# tensor of ones
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2

In [11]:
a

tensor([1., 1., 2.])

In [12]:
# consider a list of coordinates
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [13]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
points[0], points[1]

(tensor(4.), tensor(1.))

In [15]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [16]:
points.shape

torch.Size([6])

In [17]:
# better representation will be
points_alt = torch.tensor([[4.0,1.0], [5,3], [2,1]])

In [18]:
points_alt

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
# can access points with indexing
points_alt[0,1]

tensor(1.)

In [20]:
float(points_alt[0,1])

1.0

In [21]:
points_alt[0]

tensor([4., 1.])

In [22]:
# # the below doesn't work in this case as now we have multiple values
# float(points_alt[0])

In [23]:
points_alt.shape

torch.Size([3, 2])

In [24]:
# if we want a matrix of zeros of some specific shape
points_0 = torch.zeros(2,3)

In [25]:
points_0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
points_0[0]

tensor([0., 0., 0.])

##### Indexing tensors

In [27]:
points_alt

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
# Pytorch tensors can be indexed similar to python lists
points_alt[1:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points_alt[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [30]:
points_alt[1:, 0]

tensor([5., 2.])

In [31]:
# [None] adds another dimesion
points_alt_none = points_alt[None]

In [32]:
points_alt_none

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [33]:
points_alt_none.shape

torch.Size([1, 3, 2])

In [34]:
# Pytorch also has something called advanced indexing, which will come later

In [35]:
# I think pytorch does channels, rows, cols? This is different from tf, and how we naturally see an image
# when working with PyTorch, we reorder the dimensions of image data to fit its convention

##### Named tensors

In [36]:
img_t = torch.randn(3, 5, 5) # [channels, rows, columns]

In [37]:
img_t.shape

torch.Size([3, 5, 5])

In [38]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [39]:
weights.shape

torch.Size([3])

In [40]:
weights[0] + weights[1] + weights[2]

tensor(1.)

In [41]:
batch_t = torch.randn(2, 3, 5, 5) # [batch_size, channels, rows, columns]

In [42]:
# channel dimension is either 0, or 1. But from backwords it's always -3

In [43]:
# unweighted means - Think we are trying to convert an RGB to gray scale
img_gray_naive = img_t.mean(-3)

In [44]:
img_gray_naive

tensor([[ 0.7445,  0.2337, -0.2065,  0.1828, -0.0991],
        [-0.2559,  1.0023,  0.4916, -0.5487, -0.2703],
        [ 0.1969,  1.0087,  0.7151, -0.9006, -0.5158],
        [-0.0405, -1.0228, -0.0404,  0.2334,  0.5461],
        [-0.1886, -0.1697,  0.8956,  0.5965,  0.7253]])

In [45]:
img_t

tensor([[[ 1.1790, -0.6444, -0.3857,  0.3962, -0.2896],
         [ 0.8772,  0.8874,  0.6478,  0.5622,  0.3327],
         [-0.0298,  0.4361,  0.4698, -0.9689,  0.5550],
         [ 0.6249, -1.9649, -1.0084, -1.1850,  1.5948],
         [-0.7070,  0.2092,  1.2222,  0.0439,  0.2546]],

        [[ 1.4887,  0.6823, -0.6305,  1.3930,  0.6485],
         [-1.6053,  1.3864, -0.1545, -1.5221, -1.3154],
         [ 0.6864,  0.6710,  0.9948, -1.1563, -1.0468],
         [-0.4547, -0.5329,  0.2094,  1.1279, -0.1734],
         [ 0.3327, -0.9253,  0.3268,  1.3353,  1.6400]],

        [[-0.4341,  0.6632,  0.3967, -1.2408, -0.6563],
         [-0.0397,  0.7329,  0.9816, -0.6861,  0.1717],
         [-0.0660,  1.9189,  0.6808, -0.5767, -1.0556],
         [-0.2917, -0.5707,  0.6778,  0.7572,  0.2170],
         [-0.1915,  0.2069,  1.1377,  0.4103,  0.2814]]])

In [46]:
(-0.3847 + 0.6229 - 0.9177)/3 # = -0.2265

-0.2265

In [47]:
batch_gray_naive = batch_t.mean(-3)

In [48]:
batch_gray_naive

tensor([[[ 0.2491,  0.6555, -0.1823, -0.0999,  0.7110],
         [-0.3447, -1.6559,  0.6526, -0.4716,  1.0555],
         [-0.5658,  0.4449,  0.3847,  0.1282,  0.4777],
         [ 1.3819, -0.3143, -0.2909,  0.1491,  1.2747],
         [-1.4858, -0.6571,  0.0560,  0.0923,  0.2952]],

        [[-0.2949,  0.4608, -0.1266, -1.0328,  0.7191],
         [-0.2214,  0.1037,  0.4005, -0.2200,  0.3071],
         [ 0.8408, -0.5630,  0.2705,  0.1536,  0.0094],
         [-0.1787, -0.5849,  0.4972, -0.0766, -0.6492],
         [ 0.5103,  0.2006, -0.0172, -0.3173,  0.6682]]])

In [49]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [50]:
# we also have the gray scale weight

In [51]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [52]:
weights.shape

torch.Size([3])

In [53]:
weights.unsqueeze(-1).unsqueeze_(-1).shape

torch.Size([3, 1, 1])

In [54]:
weights.unsqueeze(-1).unsqueeze_(-1)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [55]:
# broadcast the weghts so that they can be multiplied with the random tensors
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [56]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

In [57]:
img_weights.shape, batch_weights.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [58]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

In [59]:
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [60]:
# can do the same with the einsum function
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)

In [61]:
img_gray_weighted_fancy.shape, batch_gray_weighted_fancy.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [62]:
(img_gray_weighted == img_gray_weighted_fancy)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [63]:
batch_gray_weighted == batch_gray_weighted_fancy

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [64]:
# It's a lot of book keeping, therefore practitioners decided to give names to the tensors

In [65]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])

In [66]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [67]:
# can add names to an existing tensor - with refine_names

In [68]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [69]:
img_named.shape, img_named.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [70]:
# can rename or drop existing names with rename method too

In [71]:
img_named_renamed = img_named.rename(..., "ch", 'r', 'c')

In [72]:
img_named_renamed.names

('ch', 'r', 'c')

In [73]:
# when operations involve tow such tensors now pytorch will also look into the names 

In [74]:
# The book only uses unnamed tensors though - as it is easier even when working outside of tensors without tha capability of naming them.

Storage of tensors

In [75]:
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])

In [76]:
# second_point = points[1]

In [77]:
# second_point.storage()

In [78]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [79]:
points.storage_offset()

0

In [80]:
points.stride()

(2, 1)

In [81]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [82]:
point_t = points.t()

In [83]:
point_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [84]:
point_t.stride()

(1, 2)