In [1]:
import torch
import numpy as np
import os

In [2]:
# Are we on GPU?

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.get_device_name()

'Tesla V100S-PCIE-32GB'

#### Tensors

In [7]:
# tensor of ones
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2

In [11]:
a

tensor([1., 1., 2.])

In [12]:
# consider a list of coordinates
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [13]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
points[0], points[1]

(tensor(4.), tensor(1.))

In [15]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [16]:
points.shape

torch.Size([6])

In [17]:
# better representation will be
points_alt = torch.tensor([[4.0,1.0], [5,3], [2,1]])

In [18]:
points_alt

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
# can access points with indexing
points_alt[0,1]

tensor(1.)

In [20]:
float(points_alt[0,1])

1.0

In [21]:
points_alt[0]

tensor([4., 1.])

In [22]:
# # the below doesn't work in this case as now we have multiple values
# float(points_alt[0])

In [23]:
points_alt.shape

torch.Size([3, 2])

In [24]:
# if we want a matrix of zeros of some specific shape
points_0 = torch.zeros(2,3)

In [25]:
points_0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
points_0[0]

tensor([0., 0., 0.])

##### Indexing tensors

In [27]:
points_alt

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
# Pytorch tensors can be indexed similar to python lists
points_alt[1:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points_alt[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [30]:
points_alt[1:, 0]

tensor([5., 2.])

In [31]:
# [None] adds another dimesion
points_alt_none = points_alt[None]

In [32]:
points_alt_none

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [33]:
points_alt_none.shape

torch.Size([1, 3, 2])

In [34]:
# Pytorch also has something called advanced indexing, which will come later

In [35]:
# I think pytorch does channels, rows, cols? This is different from tf, and how we naturally see an image
# when working with PyTorch, we reorder the dimensions of image data to fit its convention

##### Named tensors

In [36]:
img_t = torch.randn(3, 5, 5) # [channels, rows, columns]

In [37]:
img_t.shape

torch.Size([3, 5, 5])

In [38]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [39]:
weights.shape

torch.Size([3])

In [40]:
weights[0] + weights[1] + weights[2]

tensor(1.)

In [41]:
batch_t = torch.randn(2, 3, 5, 5) # [batch_size, channels, rows, columns]

In [42]:
# channel dimension is either 0, or 1. But from backwords it's always -3

In [43]:
# unweighted means - Think we are trying to convert an RGB to gray scale
img_gray_naive = img_t.mean(-3)

In [44]:
img_gray_naive

tensor([[-0.8001,  0.8877, -0.1797, -0.7456,  0.3516],
        [-0.6687,  0.3843, -0.2431,  0.2314, -0.2358],
        [ 0.3426, -0.0952,  0.1261,  0.9040,  0.0551],
        [ 0.0951, -0.0654,  0.3623,  0.0068, -0.4677],
        [ 0.2563, -0.0020,  0.4648,  0.1191, -1.1409]])

In [45]:
img_t

tensor([[[ 0.0047,  0.4983,  0.3472, -0.4876, -0.3106],
         [-1.0144,  1.7442, -0.7993,  0.3430,  1.0077],
         [ 0.1687,  0.2100,  1.2146, -0.2802, -0.1263],
         [-0.1062, -0.2323,  0.4342, -0.2162,  0.1333],
         [ 1.5472, -0.9745,  0.1066, -0.6785, -1.5719]],

        [[-0.4684,  0.7209, -0.9660, -1.2417,  0.3014],
         [-0.7863,  0.0165,  0.7355, -1.2805, -0.6744],
         [ 0.5528,  0.8260, -0.7047,  1.2193, -0.5847],
         [ 0.0437,  0.3597,  0.5756, -0.0983, -0.8290],
         [ 0.3528, -1.0096,  1.0047,  0.3288, -1.1760]],

        [[-1.9366,  1.4440,  0.0799, -0.5075,  1.0640],
         [-0.2053, -0.6080, -0.6654,  1.6317, -1.0405],
         [ 0.3064, -1.3216, -0.1315,  1.7728,  0.8762],
         [ 0.3479, -0.3235,  0.0773,  0.3350, -0.7075],
         [-1.1310,  1.9779,  0.2829,  0.7072, -0.6749]]])

In [46]:
(-0.3847 + 0.6229 - 0.9177)/3 # = -0.2265

-0.2265

In [47]:
batch_gray_naive = batch_t.mean(-3)

In [48]:
batch_gray_naive

tensor([[[ 0.6875,  0.0469,  1.4429,  0.0663, -0.1364],
         [-0.8015, -0.5903, -0.0325,  0.3303, -0.1104],
         [ 0.7650,  0.0280,  0.3556,  0.0189,  0.3670],
         [-0.1909,  0.4168, -0.0826, -1.6575,  0.8449],
         [-0.1974,  0.7443, -0.0904,  0.1640, -0.6578]],

        [[ 1.0328,  0.1965, -1.0914, -1.2866,  0.5131],
         [-1.0083, -0.1140, -0.3278,  0.0581,  0.1904],
         [-0.1528,  0.5780, -0.1733,  0.1035, -0.7069],
         [ 0.1528, -0.0887,  0.2454,  0.3072, -0.1545],
         [ 0.6126, -0.5900, -0.4092, -0.1860, -0.8718]]])

In [49]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [50]:
# we also have the gray scale weight

In [51]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [52]:
weights.shape

torch.Size([3])

In [53]:
weights.unsqueeze(-1).unsqueeze_(-1).shape

torch.Size([3, 1, 1])

In [54]:
weights.unsqueeze(-1).unsqueeze_(-1)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [55]:
# broadcast the weghts so that they can be multiplied with the random tensors
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [56]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

In [57]:
img_weights.shape, batch_weights.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [58]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

In [59]:
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [60]:
# can do the same with the einsum function
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)

In [61]:
img_gray_weighted_fancy.shape, batch_gray_weighted_fancy.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [62]:
(img_gray_weighted == img_gray_weighted_fancy)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [63]:
batch_gray_weighted == batch_gray_weighted_fancy

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [64]:
# It's a lot of book keeping, therefore practitioners decided to give names to the tensors

In [65]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])

In [66]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [67]:
# can add names to an existing tensor - with refine_names

In [68]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [69]:
img_named.shape, img_named.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [70]:
# can rename or drop existing names with rename method too

In [71]:
img_named_renamed = img_named.rename(..., "ch", 'r', 'c')

In [72]:
img_named_renamed.names

('ch', 'r', 'c')

In [73]:
# when operations involve tow such tensors now pytorch will also look into the names 

In [74]:
# The book only uses unnamed tensors though - as it is easier even when working outside of tensors without tha capability of naming them.

Storage of tensors

In [81]:
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])

In [82]:
second_point = points[1]

In [83]:
second_point.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [84]:
second_point.storage_offset()

2

In [93]:
second_point.shape

torch.Size([2])

In [94]:
points.stride()

(2, 1)